env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:unicorn/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
rules: {
  'unicorn/filename-case': [
    'error',
    {
      cases: {
        kebabCase: true,
        pascalCase: true,
      },
    },
  ],
  'react/react-in-jsx-scope': 'off',
  'unicorn/prevent-abbreviations': [
    'error',
    {
      allowList: {
        env: true,
      },
    },
  ],
  'import/prefer-default-export': 0,
}
ignorePatterns:
  - node_modules
  - .eslintrc.yml
  - vite.config.ts
  - tailwind.config.js
  - postcss.config.js
  - dist
  - docs
  - tests

